---
title: "Real World Applications 3"
subtitle: "Is a recession around the corner?"
author: "Place your name here"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

# Load packages
library(tidyverse) # core
library(tidyquant) # financial analysis
library(lubridate) # time series
library(plotly)    # Interactive visualization

# Import charts
market_indicators_fig   <- read_rds("../00_data/fig/market_indicators_fig.rds")
economic_indicators_fig <- read_rds("../00_data/fig/economic_indicators_fig.rds")
```

# Economic Dashboard {.tabset .tabset-fade}

## Market Indicators

```{r}
ggplotly(market_indicators_fig)

```

## Economic Indicators

```{r}
ggplotly(economic_indicators_fig)
```

# What is your reading of the economy?
Make your argument based on your analysis of the given charts. Discuss timing and depth of changes in the economic data relative to recessions in at least 50 words.
