---
title: "Real World Applications 6"
author: "Place your name here"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

# Survey of Professional Forecasters

The author writes on page 31:

    "At the beginning of 2001, the economy was not in recession. The fourth quarter of 2000 data had not been released but would, in time, show that the economy had grown by 2.2 percent in twelve months. Forecasters were nervous, however. The consensus forecast published by the Federal Reserve Bank of Philadelphia in February 2001 predicted a mere  0.8 percent growth in the first quarter. Also of significance, the forecasters had revised their numbers down from 3.3. percent growth in the prior survey three months earlier. That should have been a tip-off that the economy needed watching... However, executives who saw the lowered forecast in early 2001 and thereafter watched the economy closely were in a far superior position to those managers who chugged forward as if nothing were amiss."

It shows how a business manager should use macroeconomic forecasts. Go to the Federal Reserve Bank of Philadelphia and open the latest forecast report by clicking this link to [Survey of Professional Forecasters](https://www.philadelphiafed.org/surveys-and-data/real-time-data-research/survey-of-professional-forecasters). What is your reading? Is it time to watch the economy closely for an incoming downturn? Is the Philadelphia Fed's forecast consistent with the six economic indicators we analyzed in the real-world applications three assignment?

Write your answer below this line. When writing, keep the following in mind.

-   Cite the Fed's report;
-   Cite the data from the real-world applications three assignment;
-   Make recommendations to your client company. What do you think they should do now?
-   Write it in at least 200 words.

***Place your answer here***

# Business response to the questionnaire

***Question to the businesses*** Sales can swing wildly. If the company's too slow in responding to a sudden drop in sales, it could go bankrupt. If it is too slow in responding to a large upswing, it could lose its market share. It could even develop a reputation of an unreliable vendor.

Please, discuss your early warning system, if you have one.

***Response from businesses***

| Business              | Response from Business                                                                                                                                                                                                                                                                                                                                                                                                                       |
|------------|------------------------------------------------------------|
| Graponne              | The level of our car inventories which we watch closely is a great early warning indicator.  In the car business, we get to see what our competitors are selling daily so we have perspective on not just what we are selling, but how our competitors are fairing as well.  Certainly, we pay close attention to what our manufacturing partners are telling us as well as the National Auto Dealers Association, our industry trade group. |
| Bank of New Hampshire | The bank builds up loss reserves, conducts expense reviews, tries to maximize yield on assets, looks to sell less profitable assets, e.g. low yielding loans. The bank also conducts various annual stress tests and scenario analyses to identify potential problems that could arise during an adverse economic event. Corrective action is taken to mitigate these risks if the exposure is outside of acceptable ranges.                 |
| Comptus               | Our staffing is very light, and we utilize outsourcing when we are busy. In a downturn we can return to in house production.                                                                                                                                                                                                                                                                                                                 |
